version: '3.7'
services:
  redis:
    image: valkey/valkey:alpine
    container_name: valkey
    healthcheck:
      test: ['CMD-SHELL', 'valkey-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '6379:6379'
    volumes:
      - ./data/valkey:/data
    command: valkey-server --appendonly yes
  postgres:
    image: ankane/pgvector
    container_name: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: letta
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./scripts/postgres-db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
